config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :top
    resources :posts
    resources :questions, except: [:show]
    resources :feedbacks, only: %i[index show]
    resources :products
    resources :faqs
    get 'products/:id/new_child_product', to: 'products#new_child_product', as: 'new_child_product'
  end

  get :admin, to: 'admin/top#index'

  devise_for :users, path: 'devise', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  } # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  root to: 'home#index'
  resources :blog, only: %i[index show]
  resources :survey, only: %i[create]
  resources :products, only: %i[show]
  get 'category/:id', to: 'products#category', as: 'category'
  resources :faqs, only: %i[index]
  # get :blog, to: 'blog#index'
end

app/controllers/admin/faqs_controller.rb
class Admin::FaqsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_faq, only: %i[edit update destroy]
  layout 'admin'

  def index
    @product_faqs = ProductFaq.all
  end

  def new
    @product_faq = ProductFaq.new
  end

  def create
    @product_faq = ProductFaq.new(faq_params)
    if @product_faq.save!
      flash[:notice] = 'Successfully created!'
      redirect_to admin_faqs_path
    else
      flash[:alert] = 'Error!'
      render :new
    end
  end

  def edit; end

  def update
    if @product_faq.update_attributes(faq_params)
      flash[:notice] = 'Successfully updated!'
      redirect_to admin_faq_path(@product_faq)
    else
      flash[:alert] = 'Error updating!'
      render :edit
    end
  end

  def destroy
    if @product_faq.destroy
      flash[:notice] = 'Successfully deleted!'
      redirect_to admin_faqs_path
    else
      flash[:alert] = 'Error when destroying!'
    end
  end

  private

  def faq_params
    params.require(:product_faq).permit(:question, :answer)
  end

  def find_faq
    @product_faq = ProductFaq.find(params[:id])
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :find_post, only: %i[show]

  def index
    @faqs = ProductFaq.all
  end

  def show; end
end

app/views/admin/faqs/_form.html.erb
<%= bootstrap_form_for  @product_faq, url: admin_faqs_path(@product_faq) do |form| %>
  <% if @product_faq.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@product_faq.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @product_faq.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :question %>
  <%= form.cktext_area :answer, ckeditor: { language: 'en'} %>
  <%= form.submit %>
<% end %>

app/views/admin/faqs/edit.html.erb
<h2>Edit Post</h2>

<%= render "admin/faqs/form" %>

app/views/admin/faqs/index.html.erb
<div class="container">
  <div class="card">
    <!-- Default panel contents -->
    <div class="card-header">FAQ
      <div class="float-right">
        <%= link_to new_admin_faq_path do%>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>No.</th>
            <th>Question</th>
            <th>Created at</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          <% @product_faqs.each do |faq| %>
            <tr>
              <td><%= faq.id %></td>
              <td><%= faq.question %></td>
              <td><%= faq.created_at.strftime('%b %d, %Y')  %></td>
              <td>
                <%= link_to "Edit", edit_admin_faq_path(faq), class: "btn btn-info" %>
                <%= link_to 'Destroy', admin_faq_path(faq), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  
</div>

app/views/admin/faqs/new.html.erb
<h2>Create New Post</h2>

<%= render "admin/faqs/form" %>