config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :top
    resources :posts
    resources :questions, except: [:show]
    resources :feedbacks, only: %i[index show]
    resources :products
    resources :faqs
    get 'products/:id/new_child_product', to: 'products#new_child_product', as: 'new_child_product'
  end

  get :admin, to: 'admin/top#index'

  devise_for :users, path: 'devise', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  } # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  root to: 'home#index'
  resources :blog, only: %i[index show]
  resources :survey, only: %i[create]
  resources :products, only: %i[show]
  get 'category/:id', to: 'products#category', as: 'category'
  resources :faqs, only: %i[index]
  # get :blog, to: 'blog#index'
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :products,
                          join_table: :product_connections,
                          foreign_key: :parent_product_id,
                          association_foreign_key: :child_product_id

  has_many :from_products_connections,
           class_name: 'ProductConnection',
           foreign_key: 'child_product_id',
           dependent: :destroy

  has_many :from_products,
           through: 'from_products_connections',
           source: 'parent_product'

  has_many :feedbacks
  mount_uploader :thumbnail, ThumbnailUploader

  def child_product?
    product_type == PRODUCT_TYPE_CHILD
  end

  def parent_product?
    product_type == PRODUCT_TYPE_PARENT
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: %i[edit update destroy show]
  layout 'admin'

  def index
    @products = Product.where(product_type: [PRODUCT_TYPE_PARENT, nil])
  end

  def new
    @product = Product.new
  end

  def create
    ActiveRecord::Base.transaction do
      product = Product.new(product_params)
      if product.save!
        if params[:product][:parent_id]
          product.product_type = PRODUCT_TYPE_CHILD
          product.save!

          ProductConnection.create!(
            parent_product_id: Product.friendly.find(params[:product][:parent_id]).id,
            child_product_id: product.id
          )
        end

        flash[:notice] = 'Successfully created product!'
        redirect_to admin_products_path
      else
        flash[:alert] = 'Error creating new product!'
        render :new
      end
    end
  end

  def show; end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      begin
        @product.update!(
          name: product_params[:name],
          banner_image: product_params[:banner_image],
          slogan: product_params[:slogan],
          first_benefit: product_params[:first_benefit],
          first_benefit_slogan: product_params[:first_benefit_slogan],
          second_benefit: product_params[:second_benefit],
          second_benefit_slogan: product_params[:second_benefit_slogan],
          third_benefit: product_params[:third_benefit],
          third_benefit_slogan: product_params[:third_benefit_slogan]
        )

        flash[:notice] = 'Successfully updated product!'
        redirect_to admin_product_path(@product)
      rescue ActiveRecord::RecordInvalid
        flash[:alert] = 'Error updating product!'
        render :edit
      end
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = 'Successfully deleted question!'
      redirect_to admin_products_path
    else
      flash[:alert] = 'Error updating question!'
    end
  end

  def new_child_product
    @product = Product.new
    render :new
  end

  private

  # def product_params
  #   params.require(:product).permit(:name, :description, :meta_desc, :thumbnail)
  # end

  def product_params
    params.require(:product).permit(
      :name,
      :title, :title_tag,
      :description, :thumbnail,
      :meta_desc, :meta_robot, :meta_keys,
      :h1_tag,
      :sec_1_title, :sec_1_content,
      :sec_2_title, :sec_2_content,
      :sec_3_title, :sec_3_content
    )
  end

  def faq_params
    params.require(:product).permit(faq: %i[question answer id])
  end

  def find_product
    @product = Product.friendly.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[edit update destroy show category]

  def show
    @questions = Question.all
  end

  def category; end

  def edit; end

  private

  def find_product
    @product = Product.friendly.find(params[:id])
  end
end

app/views/admin/products/_product_child_form.html.erb
<%= bootstrap_form_for [:admin, @product] do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@product.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name %>
  <div class="card">
    <div class="card-header">Product Content</div>
    <div class="card-body">
      <div class="form-group">
        <%= form.text_field :title %>
      </div>
      <div class="form-group">
        <label for="title_tag">Title tag</label>
        <div class="form-control html_input" id="title_tag"></div>
        <%= form.text_field :title_tag %>
      </div>
      <div class="form-group">
        <label for="product_first_benefit">Description</label>
        <%= form.cktext_area :description, ckeditor: { language: 'en'} %>
      </div>
      <div class="form-group">
        <%= image_tag(@product.thumbnail, alt: 'Image', class: "product_thumbnail") if @product.thumbnail? %>
        <%= form.file_field :thumbnail %>
      </div>
      <div class="form-group">
        <label for="meta_desc">Meta description tag</label>
        <div class="form-control html_input" id="meta_desc"></div>
        <%= form.text_field :meta_desc %>
      </div>
      <div class="form-group">
        <label for="meta_robot">Meta robot tag</label>
        <div class="form-control html_input" id="meta_robot"></div>
        <%= form.text_field :meta_robot %>
      </div>
      <div class="form-group">
        <label for="meta_keys">Meta keys tag</label>
        <div class="form-control html_input" id="meta_keys"></div>
        <%= form.text_field :meta_keys %>
      </div>
      <div class="form-group">
        <label for="h1_tag">H1 tag</label>
        <div class="form-control html_input" id="h1_tag"></div>
        <%= form.text_field :h1_tag %>
      </div>
      <div class="form-group">
        <%= form.text_field :sec_1_title, label: "Section 1 title" %>
      </div>
      <div class="form-group">
        <label for="product_third_benefit_slogan">Section 1 content</label>
        <%= form.cktext_area :sec_1_content, ckeditor: { language: 'en'} %>
      </div>
      <div class="form-group">
        <%= form.text_field :sec_2_title, label: "Section 2 title" %>
      </div>
      <div class="form-group">
        <label for="product_third_benefit_slogan">Section 2 content</label>
        <%= form.cktext_area :sec_2_content, ckeditor: { language: 'en'} %>

      </div>
      <div class="form-group">
        <%= form.text_field :sec_3_title, label: "Section 3 title" %>
      </div>
      <div class="form-group">
        <label for="product_third_benefit_slogan">Section 3 content</label>
        <%= form.cktext_area :sec_3_content, ckeditor: { language: 'en'} %>

      </div>
    </div>
  </div>
  <% if params[:id].present? %>
    <%= hidden_field_tag "product[parent_id]", params[:id] %>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/admin/products/_product_form.html.erb
<%= bootstrap_form_for [:admin, @product] do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@product.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name %>
  <div class="card">
    <div class="card-header">Product Content</div>
    <div class="card-body">
      <div class="form-group">
        <label for="product_banner_image">Description</label>
        <%= form.cktext_area :description, ckeditor: { language: 'en'} %>
      </div>
      <div class="form-group">
        <label for="meta_desc">Meta tag description</label>
        <div class="form-control html_input" id="meta_desc"></div>
        <textarea name="product[meta_desc]" id='textarea_meta_desc' style="display: none;"><%= @product.meta_desc.to_s %></textarea>
      </div>
      <div class="form-group">
        <%= image_tag(@product.thumbnail, alt: 'Image', class: "product_thumbnail") if @product.thumbnail? %>
        <%= form.file_field :thumbnail %>
      </div>
    </div>
  </div>
  <% if params[:id] %>
    <%= hidden_field_tag "product[parent_id]", params[:id] %>
  <% end %>
  <%= form.submit %>
<% end %>

app/views/admin/products/edit.html.erb
<h2>Edit Product</h2>

<% if @product.child_product? %>
  <%= render "admin/products/product_child_form" %>
<% else %>
  <%= render "admin/products/product_form" %>
<% end %>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="card">
    <!-- Default panel contents -->
    <div class="card-header">Products
      <div class="float-right">
        <%= link_to new_admin_product_path do%>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
    <div class="card-body">
      <table class="table">
        <thead>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <th>Created at</th>
            <th>Action</th>
            <th>Child product</th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td><%= product.name %></td>
              <td><%= product.created_at.strftime('%b %d, %Y')  %></td>
              <td>
                <%= link_to "", product_path(product), class: "btn btn-primary glyphicon glyphicon-info-sign" %>
                <%= link_to "", edit_admin_product_path(product), class: "btn btn-info glyphicon glyphicon-edit" %>
                <%= link_to "", admin_new_child_product_path(product), class: "btn btn-info glyphicon glyphicon-plus", alt: "Add sub product" %>
                <%= link_to "", admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-minus" %>
              </td>
              <td>
                <% if product.products %>
                  <ul class="list-group list-group-flush">
                    <% product.products.each do |child_product| %>
                      <li class="list-group-item">
                        <%= child_product.name %>
                        <%= link_to "", admin_product_path(child_product), class: "btn btn-primary btn btn-primary glyphicon glyphicon-info-sign" %>
                        <%= link_to "", edit_admin_product_path(child_product), class: "btn btn-info glyphicon glyphicon-edit" %>
                        <%= link_to "", admin_product_path(child_product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-minus" %>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  
</div>

app/views/admin/products/new.html.erb
<h2>Create New Product</h2>

<% if params[:id] %>
  <%= render "admin/products/product_child_form" %>
<% else %>
  <%= render "admin/products/product_form" %>
<% end %>