config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :top
    resources :posts
    resources :questions, except: [:show]
    resources :feedbacks, only: %i[index show]
    resources :products
    resources :faqs
    get 'products/:id/new_child_product', to: 'products#new_child_product', as: 'new_child_product'
  end

  get :admin, to: 'admin/top#index'

  devise_for :users, path: 'devise', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  } # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  root to: 'home#index'
  resources :blog, only: %i[index show]
  resources :survey, only: %i[create]
  resources :products, only: %i[show]
  get 'category/:id', to: 'products#category', as: 'category'
  resources :faqs, only: %i[index]
  # get :blog, to: 'blog#index'
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :products,
                          join_table: :product_connections,
                          foreign_key: :parent_product_id,
                          association_foreign_key: :child_product_id

  has_many :from_products_connections,
           class_name: 'ProductConnection',
           foreign_key: 'child_product_id',
           dependent: :destroy

  has_many :from_products,
           through: 'from_products_connections',
           source: 'parent_product'

  has_many :feedbacks
  mount_uploader :thumbnail, ThumbnailUploader

  def child_product?
    product_type == PRODUCT_TYPE_CHILD
  end

  def parent_product?
    product_type == PRODUCT_TYPE_PARENT
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: %i[edit update destroy show]
  layout 'admin'

  def index
    @products = Product.where(product_type: [PRODUCT_TYPE_PARENT, nil])
  end

  def new
    @product = Product.new
  end

  def create
    ActiveRecord::Base.transaction do
      product = Product.new(product_params)
      if product.save!
        if params[:product][:parent_id]
          product.product_type = PRODUCT_TYPE_CHILD
          product.save!

          ProductConnection.create!(
            parent_product_id: Product.friendly.find(params[:product][:parent_id]).id,
            child_product_id: product.id
          )
        end

        flash[:notice] = 'Successfully created product!'
        redirect_to admin_products_path
      else
        flash[:alert] = 'Error creating new product!'
        render :new
      end
    end
  end

  def show; end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      begin
        @product.update!(
          name: product_params[:name],
          banner_image: product_params[:banner_image],
          slogan: product_params[:slogan],
          first_benefit: product_params[:first_benefit],
          first_benefit_slogan: product_params[:first_benefit_slogan],
          second_benefit: product_params[:second_benefit],
          second_benefit_slogan: product_params[:second_benefit_slogan],
          third_benefit: product_params[:third_benefit],
          third_benefit_slogan: product_params[:third_benefit_slogan]
        )

        flash[:notice] = 'Successfully updated product!'
        redirect_to admin_product_path(@product)
      rescue ActiveRecord::RecordInvalid
        flash[:alert] = 'Error updating product!'
        render :edit
      end
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = 'Successfully deleted question!'
      redirect_to admin_products_path
    else
      flash[:alert] = 'Error updating question!'
    end
  end

  def new_child_product
    @product = Product.new
    render :new
  end

  private

  # def product_params
  #   params.require(:product).permit(:name, :description, :meta_desc, :thumbnail)
  # end

  def product_params
    params.require(:product).permit(
      :name,
      :title, :title_tag,
      :description, :thumbnail,
      :meta_desc, :meta_robot, :meta_keys,
      :h1_tag,
      :sec_1_title, :sec_1_content,
      :sec_2_title, :sec_2_content,
      :sec_3_title, :sec_3_content
    )
  end

  def faq_params
    params.require(:product).permit(faq: %i[question answer id])
  end

  def find_product
    @product = Product.friendly.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: %i[edit update destroy show category]

  def show
    @questions = Question.all
  end

  def category; end

  def edit; end

  private

  def find_product
    @product = Product.friendly.find(params[:id])
  end
end

app/views/products/_content.html.erb
<div class="events-lp-default fwd">
<div id="tiki-fwd">
   <div data-reactroot="">
      <div class="banner" style="cursor: pointer;"><%= image_tag @product.product_content.banner_image, style: "width: 100%;" %></div>
      <div class="block-benerfit">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <h2 class="text-center text-organe">“<%= @product.product_content.slogan %>”</h2>
               </div>
            </div>
            <div class="row">
              <div class="col text-center item">
                 <%= image_tag @product.product_content.first_benefit %><br>
                 <span class="lable">
                    <%= @product.product_content.first_benefit_slogan %>
                 </span>
              </div>
              <div class="col text-center item">
                 <%= image_tag @product.product_content.second_benefit %><br>
                 <span class="lable">
                    <%= @product.product_content.second_benefit_slogan %>
                 </span>
              </div>
              <div class="col text-center item">
                 <%= image_tag @product.product_content.third_benefit %><br>
                 <span class="lable">
                    <%= @product.product_content.third_benefit_slogan %>
                 </span>
              </div>
            </div>
            <div class="row">
               <% @product.product_faqs.each do |faq| %>
                  <div class="col-md-6">
                     <h5 class="table-menu">
                      <div class="row-menu title" data-toggle="collapse" data-target="#collapse_<%= faq.id %>" aria-expanded="true" aria-controls="collapse_<%= faq.id %>">
                         <span class="icon"></span><%= faq.question %>
                      </div>
                     </h5>
                     <div id="collapse_<%= faq.id %>" class="collapse">
                       <section class="slidergroup height-transition height-transition-show">
                         <article>
                           <%= faq.answer %>
                         </article>
                       </section>
                     </div>
                  </div>
               <% end %>
            </div>
         </div>
         <picture>
            <source media="(min-width: 768px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-1.png">
            <source media="(min-width: 320px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-1.png">
            <img src="https://vcdn.tikicdn.com/lp/fwd/img/bg-1.png" alt="" style="width: 100%;">
         </picture>
      </div>
      <%= render 'survey_form' %>
   </div>
</div>
     
    
    
     
     
    <script>
        var order_holded = '0';  
    </script>

    <script>
        var upload_reminder = '0';  
    </script>
    


</div>         





        

    
    

app/views/products/_survey_form.html.erb
<div class="contact">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-lg-9 contact_form_col">
        <div class="section_title_container">
          <div class="section_subtitle">Survey</div>
          <div class="section_title">Please help us answer few question here</div>
        </div>
        <div class="contact_form_container">
          <%= form_tag survey_index_path, class: "contact_form" do %>
            <div class="row">
              <div class="col-md-3">
                <td><label class="survey_label_no_vni_font">Họ và tên</label></td>
              </div>
              <div class="col-md-9">
                <%= text_field_tag "feedback[full_name]", nil, class: "input_item", placeholder: "Your full name", required: true %>
              </div>
              <div class="col-md-3">
                <td><label class="survey_label_no_vni_font">Ngày sinh</label></td>
              </div>
              <div class="col-md-9">
                <%= select_day(Date.today, {field_name: 'day'}, class: "dropdown_item input_item col-md-3") %>
                <%= select_month(Date.today, {field_name: 'month'}, class: "dropdown_item input_item col-md-3") %>
                <%= select_year(Date.today, {field_name: 'year'}, class: "dropdown_item input_item col-md-3") %>
              </div>
              <div class="col-md-3">
                <td><label class="survey_label_no_vni_font">Giới tính</label></td>
              </div>
              <div class="col-md-9">
                <%= select("feedback", "gender", GENDER_ARRAY , {include_blank: 'Please select one' }, { required: true, class: 'dropdown_item input_item' }) %>
              </div>
              <div class="col-md-3">
                <td><label class="survey_label">Số điện thoại</label></td>
              </div>
              <div class="col-md-9">
                <%= text_field_tag "feedback[phone_number]", nil, class: "input_item", placeholder: "Your phone number", required: true, type: "number" %>
              </div>
              <%= hidden_field_tag "feedback[product_id]", @product.id %>
              <% @questions.each do |question| %>
                <div class="col-md-12">
                  <%= text_field_tag "feedback[answers[]answer]", nil, class: "input_item", placeholder: question.question, required: true %>
                  <%= hidden_field_tag "feedback[answers[]question_id]", question.id %>
                </div>
              <% end %>
              <div class="col-md-12">
                <button id="contact_btn" type="submit" class="contact_button trans_200" value="Submit">submit</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_survey_form_old.html.erb
<div class="block-personal form1">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
            <h2 class="text-center text-organe">
               <!-- react-text: 127 -->Nhập thông tin để xem<!-- /react-text --><br><!-- react-text: 129 --> quyền lợi và phí bảo hiểm của tôi<!-- /react-text -->
            </h2>
         </div>
      </div>
      <div class="row">
         <div class="col-md-12">
            <div class="form-group date-out">
                <%= form_tag survey_index_path, class: "contact_form" do %>
                  <table>
                     <tbody>
                        <tr>
                           <td><label class="control-label">Ngày sinh</label></td>
                           <td class="col-date">
                              <div>
                                 <%= date_select :birthday, order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100, class: "birthday-picker" %>

                                 <fieldset class="birthday-picker">

                                    <select class="birth-day form-control" name="birth[day]">
                                       <option value="0" class="default">Chọn Ngày</option>
                                       <option value="1">1</option>
                                       <option value="2">2</option>
                                       <option value="3">3</option>
                                       <option value="4">4</option>
                                       <option value="5">5</option>
                                       <option value="6">6</option>
                                       <option value="7">7</option>
                                       <option value="8">8</option>
                                       <option value="9">9</option>
                                       <option value="10">10</option>
                                       <option value="11">11</option>
                                       <option value="12">12</option>
                                       <option value="13">13</option>
                                       <option value="14">14</option>
                                       <option value="15">15</option>
                                       <option value="16">16</option>
                                       <option value="17">17</option>
                                       <option value="18">18</option>
                                       <option value="19">19</option>
                                       <option value="20">20</option>
                                       <option value="21">21</option>
                                       <option value="22">22</option>
                                       <option value="23">23</option>
                                       <option value="24">24</option>
                                       <option value="25">25</option>
                                       <option value="26">26</option>
                                       <option value="27">27</option>
                                       <option value="28">28</option>
                                       <option value="29">29</option>
                                       <option value="30">30</option>
                                       <option value="31">31</option>
                                    </select>
                                    <select class="birth-month form-control" name="birth[month]">
                                       <option value="0" class="default">Chọn Tháng</option>
                                       <option value="1">01</option>
                                       <option value="2">02</option>
                                       <option value="3">03</option>
                                       <option value="4">04</option>
                                       <option value="5">05</option>
                                       <option value="6">06</option>
                                       <option value="7">07</option>
                                       <option value="8">08</option>
                                       <option value="9">09</option>
                                       <option value="10">10</option>
                                       <option value="11">11</option>
                                       <option value="12">12</option>
                                    </select>
                                    <select class="birth-year form-control" name="birth[year]">
                                       <option value="0" class="default">Chọn Năm</option>
                                       <option value="2000">2000</option>
                                       <option value="1999">1999</option>
                                       <option value="1998">1998</option>
                                       <option value="1997">1997</option>
                                       <option value="1996">1996</option>
                                       <option value="1995">1995</option>
                                       <option value="1994">1994</option>
                                       <option value="1993">1993</option>
                                       <option value="1992">1992</option>
                                       <option value="1991">1991</option>
                                       <option value="1990">1990</option>
                                       <option value="1989">1989</option>
                                       <option value="1988">1988</option>
                                       <option value="1987">1987</option>
                                       <option value="1986">1986</option>
                                       <option value="1985">1985</option>
                                       <option value="1984">1984</option>
                                       <option value="1983">1983</option>
                                       <option value="1982">1982</option>
                                       <option value="1981">1981</option>
                                       <option value="1980">1980</option>
                                       <option value="1979">1979</option>
                                       <option value="1978">1978</option>
                                       <option value="1977">1977</option>
                                       <option value="1976">1976</option>
                                       <option value="1975">1975</option>
                                       <option value="1974">1974</option>
                                       <option value="1973">1973</option>
                                       <option value="1972">1972</option>
                                       <option value="1971">1971</option>
                                       <option value="1970">1970</option>
                                       <option value="1969">1969</option>
                                       <option value="1968">1968</option>
                                    </select>
                                    <input type="hidden" name="birthdate" id="birthdate">
                                 </fieldset>
                              </div>
                           </td>
                        </tr>
                        <tr>
                           <td></td>
                           <td>
                              <p class="error birthday">Vui lòng chọn ngày sinh</p>
                           </td>
                        </tr>
                        <tr>
                           <td><label class="control-label">Giới tính</label></td>
                           <td>
                              <div class="gender">
                                 <div class=" icon">
                                    <p>Nam</p>
                                    <img src="https://vcdn.tikicdn.com/lp/fwd/img/icon-male.png">
                                 </div>
                                 <div class=" icon">
                                    <p>Nữ</p>
                                    <img src="https://vcdn.tikicdn.com/lp/fwd/img/icon-female.png">
                                 </div>
                              </div>
                           </td>
                        </tr>
                        <tr>
                           <td></td>
                           <td>
                              <p class="error gender">Vui lòng chọn giới tính</p>
                           </td>
                        </tr>
                        <tr>
                           <td colspan="2" style="font-size: 12px; text-align: center;">
                              <!-- react-text: 177 -->Nếu bạn không nằm trong độ tuổi 18-50 hoặc muốn mua gói bảo hiểm có giá trị lớn hơn, <!-- /react-text --><a target="_blank" href="https://www.fwd.com.vn/vi/lien-he/" style="color: rgb(254, 117, 43);">vui lòng liên hệ với chúng tôi</a>
                           </td>
                        </tr>
                        <tr>
                           <td></td>
                           <td><a href="javascript:;" class="btn-tham-gia" style="margin-top: 20px;">Xem gói bảo hiểm</a></td>
                        </tr>
                     </tbody>
                  </table>
               <% end %>
            </div>
         </div>
      </div>
      <div class="row"></div>
   </div>
   <picture>
      <source media="(min-width: 768px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-2.png?v=2">
      <source media="(min-width: 320px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-2.png?v=2">
      <img src="https://vcdn.tikicdn.com/lp/fwd/img/bg-2.png?v=2" alt="" style="width: 100%;">
   </picture>
</div>
<div class="block-choose-care form2">
   <div class="container">
      <div class="row">
         <div class="col-md-6 text-right">
            <div class="item text-center">
               <div class="lable">Gói bảo hiểm của tôi</div>
               <div class="content">
                  <span>Quyền lợi</span>
                  <h3></h3>
                  <ul>
                     <li>Được chi trả toàn bộ một lần khi phát hiện bệnh ung thư.</li>
                     <li>Khi quyền lợi được chi trả, gói bảo hiểm kết thúc.</li>
                  </ul>
                  <hr>
                  <div><span>Phí bảo hiểm</span><span class="text-note">Bạn hãy nhập ngày sinh, giới tính và gói bảo hiểm ở trên để biết phí bảo hiểm</span></div>
               </div>
            </div>
         </div>
         <div class="col-md-6 text-left">
            <div class="you-now">
               <div class="content text-center">
                  <img alt="" src="https://vcdn.tikicdn.com/lp/fwd/img/icon-light.png">
                  <p>Bạn có biết?</p>
                  <!-- react-text: 209 -->Bạn được bảo hiểm trong 5 năm với mức phí mỗi năm không đổi. Để duy trì hiệu lực gói bảo hiểm, bạn chỉ cần đóng phí hàng năm trong thời gian trên.<!-- /react-text -->
               </div>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-md-12 text-center" style="margin-top: 40px;"><a href="javascript:;" class="btn-tham-gia">Đăng ký ngay</a></div>
      </div>
   </div>
   <picture>
      <source media="(min-width: 768px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-3.png?v=2">
      <source media="(min-width: 320px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-3.png?v=2">
      <img src="https://vcdn.tikicdn.com/lp/fwd/img/bg-3.png?v=2" alt="" style="width: 100%;">
   </picture>
</div>
<div class="block-bang-gia">
   <div class="container">
      <div class="row">
         <div class="col-md-12 text-center">
            <p class="content-download text-center"><a target="_blank" href="https://vcdn.tikicdn.com/lp/fwd/pdf/[VNFWD]_CC_Brochure_v6_op4.PDF" title="Thông tin sản phẩm">Thông tin sản phẩm</a><a target="_blank" href="/fwd/bao-hiem-ung-thu/cau-hoi-thuong-gap" title="Các câu hỏi thường gặp">Các câu hỏi thường gặp</a><a target="_blank" href="https://vcdn.tikicdn.com/lp/fwd/pdf/quy-tac-dieu-khoan-(Interactive).pdf?v=1" title="Quy tắc &amp; Điều khoản">Quy tắc &amp; Điều khoản</a></p>
         </div>
      </div>
   </div>
   <picture>
      <source media="(min-width: 768px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-4.png">
      <source media="(min-width: 320px)" srcset="https://vcdn.tikicdn.com/lp/fwd/img/bg-4.png">
      <img src="https://vcdn.tikicdn.com/lp/fwd/img/bg-4.png" alt="" style="width: 100%;">
   </picture>
</div>

app/views/products/category.html.erb
<div class="site">
  <%= render 'layouts/header' %>
  
  <div class="site-content">
    <div class="section-cmn section-breadcrumb">
      <div class="max-width">
        <div class="title">Sản phẩm</div>
        <ol class="list">
          <li><%= link_to 'Trang chủ', root_path %></li>
          <li><a href="#">Sản phẩm</a></li>
          <li><%= @product.name %></a></li>
        </ol>
      </div>
    </div><!-- end .section-breadcrumb -->

    <div class="section-main-content">
      <div class="max-width">
        <ul class="list-category">
          <% @product.products.each do |child_product| %>
            <li>
              <div class="cat-img"><%= image_tag(child_product.thumbnail, alt: 'Image') if child_product.thumbnail? %></div>
              <div class="cat-desc">
                <div class="title"><%= child_product.name %></div>
                <p class="desc"><%= strip_tags(child_product.description.truncate_words(50)) %></p>
                <p class="view"><%= link_to "Xem thêm >>", product_path(child_product) %></p>
              </div>
            </li>
          <% end %>

        </ul>
      </div>
    </div><!-- end .section-main-content -->
  </div><!-- end .site-content -->

  <%= render 'layouts/footer' %>

</div><!-- end #site -->

app/views/products/show.html.erb
<div class="site">
  <%= render 'layouts/header' %>
  <% parent_product = @product.from_products.first %>
  
  <div class="site-content">
    <div class="section-cmn section-breadcrumb">
      <div class="max-width">
        <div class="title">Cuộc sống tươi đẹp</div>
        <ol class="list">
          <li><%= link_to 'Trang chủ', root_path %></li>
          <li><a href="#">Sản phẩm</a></li>
          <li><a href="<%= category_path(parent_product) %>"><%= parent_product.name %></a></li>
          <li><%= @product.name %></li>
        </ol>
      </div>
    </div><!-- end .section-breadcrumb -->

    <div class="section-main-content">
      <div class="max-width">
        <%= render 'layouts/side_bar' %>
        <div class="content">
          <div class="post">
            <h3 class="title" id="sec_1"><%= @product.sec_1_title %></h3>
            <%= @product.sec_1_content.html_safe %>
          </div>
          <div class="post">
            <h3 class="title" id="sec_2"><%= @product.sec_2_title %></h3>
            <%= @product.sec_2_content.html_safe %>
          </div>
          <div class="post">
            <h3 class="title" id="sec_3"><%= @product.sec_3_title %></h3>
            <%= @product.sec_3_content.html_safe %>
          </div>
        </div>
      </div>
    </div><!-- end .section-main-content -->
  </div><!-- end .site-content -->
  <%= render 'layouts/footer' %>

</div><!-- end #site -->